// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcaipsvupiluoonvqoaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjYWlwc3Z1cGlsdW9vbnZxb2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODA3MjQsImV4cCI6MjA3NDI1NjcyNH0.WV48liA95QVoUbqoFR_KkZn6wv0p9xpjQ-pU2voR-Cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});